use mydb;

ALTER TABLE users
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE users
ADD COLUMN username VARCHAR(30) UNIQUE NOT NULL,
ADD COLUMN password VARCHAR(255) NOT NULL