use mydb;

CREATE TABLE tasks (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL,
	description TEXT,
	category_id BIGINT,
	status_id BIGINT NOT NULL DEFAULT 0,
	due_date DATE,
	priority VARCHAR(50),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE categories (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	description TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(name)
);

CREATE TABLE statuses (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	description TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(name)
);


CREATE TABLE assignments (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	user_id BIGINT NOT NULL,
	task_id BIGINT NOT NULL,
	assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE tasks
ADD CONSTRAINT FK_Category_Id FOREIGN KEY (category_id) REFERENCES categories(id);

ALTER TABLE tasks
ADD CONSTRAINT FK_Status_Id
FOREIGN KEY (status_id) REFERENCES statuses(id);

ALTER TABLE assignments
ADD CONSTRAINT FK_User_Id
FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE assignments
ADD CONSTRAINT FK_Task_Id
FOREIGN KEY (task_id) REFERENCES tasks(id);